### ISSUE TITLE
Define backend development procedures and best practices

### ISSUE THREAD

**Issue by srdocivana** [CloudHorizon/Standards#5]
Define basic backend standards (PCR standards) and development procedures

- REST API
- PSR standards
- EditorConfig
- Object oriented principles
- Review https://github.com/CloudHorizon/Developer-Guide/tree/master/BestPractices

**Comment by srdocivana** [comment]
In the [Style Guides and Best Practices](https://github.com/CloudHorizon/Developer-Guide/tree/master/BestPractices), you can find two new/updated folders:
- [JSON-API](https://github.com/CloudHorizon/Developer-Guide/tree/master/BestPractices/JSON-API)
- [PHP](https://github.com/CloudHorizon/Developer-Guide/tree/master/BestPractices/PHP)

For the API standards, I just added links to Useful resources, where you can find the Specification, Recommendations, Examples and Implementations.

For the PHP standards, I added PSR-1 Basic Coding Standards, PSR-2 Coding Style Guide, PSR-2 Coding Style Guide Additions and Object-Oriented Bootcamp (link to Laracasts tutorials).

**Comment by stojanovic** [comment]
:+1:
